# Generated by Django 5.2.7 on 2025-10-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
