# Generated by Django 5.2.7 on 2025-10-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myself',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
