# Generated by Django 5.2.7 on 2025-10-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_rename_creat_at_myself_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myself',
            old_name='discription',
            new_name='description',
        ),
    ]
